[package]
name = "zip7"
description = "ZIP unpacking bindings from 7z"
edition = "2024"
version = "0.0.1"

[dependencies]
derive_more = { version = "2.0", features = ["display", "from"] }
zip7-sys = { path = "./zip7-sys" }
